# DATA PRE PROCESSING

### Importing Libraries

In [374]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing Dataset

In [390]:
dataset = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [397]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [402]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [400]:
x = dataset.iloc[:, 5].values
y = dataset.iloc[:, 1].values


### Checking if there are empty values

In [378]:
# Checking for empty values on the feature and its size relative to the total number of data as this can affect the performance of the model.
no_of_nan = dataset["Age"].isna().sum()
total_row = len(x)
x_nan = (no_of_nan / total_row) * 100

print("The total number of nan values on column 'Age' is "+ str(no_of_nan))
print("The total number of data or obeservation is " + str(total_row))
print("The percentage of nana values on Column 'Age' is " + str("%.2f" % x_nan) + "%")

The total number of nan values on column 'Age' is 177
The total number of data or obeservation is 891
The percentage of nana values on Column 'Age' is 19.87%


In [379]:
x = x.reshape(-1, 1)
y = y.reshape(-1, 1)

### Substituting the Missing Values

In [380]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)

In [381]:
x.ndim

2

### Splitting the dataset into the Training set and Test set


In [382]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

### Feature Scaling 

In [383]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# TRAINING THE MODEL

In [384]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# PREDICTING TEST RESULTS

In [385]:
print(classifier.predict(sc.transform([[60]])))

[0]


### Predicting the Test Set Results 

In [388]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]

# EVALUATING MODEL PERFORMANCE

### Making Confusion Matrix 

In [389]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[102   8]
 [ 57  12]]


0.6368715083798883

### PREPARING FOR TEST DATA RESULT SUBMISSION 

In [429]:
test_var = test.iloc[:,4].values
test_id = test.iloc[:, 0].values

In [430]:
test_var = test_var.reshape(-1, 1)

In [431]:
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(test_var)
test_var = imputer.transform(test_var)

In [432]:
test_var

array([[34.5 ],
       [47.  ],
       [62.  ],
       [27.  ],
       [22.  ],
       [14.  ],
       [30.  ],
       [26.  ],
       [18.  ],
       [21.  ],
       [30.27],
       [46.  ],
       [23.  ],
       [63.  ],
       [47.  ],
       [24.  ],
       [35.  ],
       [21.  ],
       [27.  ],
       [45.  ],
       [55.  ],
       [ 9.  ],
       [30.27],
       [21.  ],
       [48.  ],
       [50.  ],
       [22.  ],
       [22.5 ],
       [41.  ],
       [30.27],
       [50.  ],
       [24.  ],
       [33.  ],
       [30.27],
       [30.  ],
       [18.5 ],
       [30.27],
       [21.  ],
       [25.  ],
       [30.27],
       [39.  ],
       [30.27],
       [41.  ],
       [30.  ],
       [45.  ],
       [25.  ],
       [45.  ],
       [30.27],
       [60.  ],
       [36.  ],
       [24.  ],
       [27.  ],
       [20.  ],
       [28.  ],
       [30.27],
       [10.  ],
       [35.  ],
       [25.  ],
       [30.27],
       [36.  ],
       [17.  ],
       [32.  ],
       [

In [433]:
submission_preds = classifier.predict(test_var)

In [434]:
submission_preds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [436]:
df = pd.DataFrame({"PassengerId":test_id, "Survived":submission_preds,})

In [439]:
df

PassengerId  Survived
0            892         1
1            893         1
2            894         1
3            895         1
4            896         1
..           ...       ...
413         1305         1
414         1306         1
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [441]:
df.to_csv('Submission.csv', index=False)